apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  
  labels:
    name: myapp-pipeline
  name: myapp-pipeline
 
spec:
 
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
            pipeline {
              agent {
                node {
                  label 'maven' 
                }
              }
              options {
                timeout(time: 20, unit: 'MINUTES') 
              }
              stages {
                  
                stage('CheckoutStage') {
                    steps {
                        script {
                            git "https://github.com/demo-manish/demoapp.git"
                        }
                    }
                }

                stage('build') {
                    steps {
                        script {
                            sh "mvn install" 
                        }
                    }
                }
                
                stage('UnitTest') {
                    steps {
                        script {
                            sh "mvn test"
                        }
                    }
                }
                
                stage ('DockerStage') {
                    steps {
                        script {
                            sh "oc start-build myapp --from-dir . --follow"
                        }
                    }
                    
                }
              }
            }
        
    type: JenkinsPipeline
 